"""초기 스키마 - 충전소, 충전기, 상태 로그

Revision ID: d5a0e261939f
Revises: 
Create Date: 2026-09-13 17:17:57.573692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a0e261939f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_stations',
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('addr', sa.String(length=300), nullable=True),
    sa.Column('sido', sa.String(length=50), nullable=True),
    sa.Column('gugun', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('chargers',
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.Column('charger_id', sa.String(length=10), nullable=False),
    sa.Column('charger_type', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('is_limited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.station_id'], ),
    sa.PrimaryKeyConstraint('station_id', 'charger_id')
    )
    op.create_table('charger_status_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.Column('charger_id', sa.String(length=10), nullable=False),
    sa.Column('stat', sa.String(length=5), nullable=True),
    sa.Column('stat_upd_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_charge_start_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_charge_end_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_charge_start_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id', 'charger_id'], ['chargers.station_id', 'chargers.charger_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_status_log_lookup', 'charger_status_log', ['station_id', 'charger_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_log_lookup', table_name='charger_status_log')
    op.drop_table('charger_status_log')
    op.drop_table('chargers')
    op.drop_table('charging_stations')
    # ### end Alembic commands ###
